---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install required Packages
  apt:
    name: "{{ required_packages }}"
    state: present
    update_cache: true
  become: true

- name: Create Docker keyrings directory
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  shell: "curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg"
  args:
    creates: /etc/apt/keyrings/docker.gpg

- name: Set permissions for Docker GPG key
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'

- name: Get Debian codename
  shell:
    cmd: "grep 'VERSION_CODENAME' /etc/os-release | awk -F'=' '{print $2}'"
  register: debian_codename

- name: Get system arch
  command: dpkg --print-architecture
  register: system_architecture

- name: Add Docker APT Repository
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: |
      deb [arch="{{ system_architecture.stdout }}" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian "{{ debian_codename.stdout }}" stable
    create: yes

- name: Update APT cache after adding repository
  apt:
    update_cache: yes

- name: Install Docker
  apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true
  become: true

- name: Start service Docker, if not started
  ansible.builtin.service:
    name: docker
    state: started